rpl_publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: [4,4,5,5,5,0]

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6"]
    pos1: [-1.57, -1.05, -2.27, 0.0, 1.57, 0.0]
    pos2: [-1.57, -1.05, -2.27, -1.40, 1.57, 0.0]
    pos3: [-1.57, -1.35, -2.61, -0.75, 1.57, 0.0]
    pos4: [-1.57, -1.05, -2.27, -1.40, 1.57, 0.0]
    pos5: [-1.57, -1.05, -2.27, 0.0, 1.57, 0.0]
    pos6: [-1.57, 0.0, -2.27, -0.87, 1.57, 0.0]

    gripper_pos: [0,0,38,38,38,38]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      shoulder_pan_joint: [-1.6,-1.5]
      shoulder_lift_joint: [-0.1,0.1]
      elbow_joint: [-2.3,-2.2]
      wrist_1_joint: [-0.9,-0.8]
      wrist_2_joint: [1.5,1.6]
      wrist_3_joint: [-0.1,0.1]